backend:
  name: github
  repo: premkumar-meta/static-sites
  branch: main
  base_url: https://api.staging.proptoll.com 
  # base_url: http://localhost:8080
  auth_endpoint: /api/auth


display_url: https://test1.proptoll.com/
site_url: https://test1.proptoll.com/

#npx netlify-cms-proxy-server
# local_backend: true  # Specifies that the backend is local
# site_url: http://localhost:8081 # Specifies the site URL for the local backend


media_folder: "test1/static/images/uploads"
public_folder: "/images/uploads"
editor:
  preview: true
collections:
- name: "blog" # Used in routes, e.g., /admin/collections/blog
  label: "Blog" # Used in the UI
  folder: "test1/content/blog/posts" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields: # The fields for each document, usually in front matter
    - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
    - { label: "Title", name: "title", widget: "string" }
    - { label: "Publish Date", name: "date", widget: "datetime" }
    - { label: "Featured Image", name: "thumbnail", widget: "image" }
    - { label: "Body", name: "body", widget: "markdown" }
    - { label: "Weight", name: "weight", widget: "number", default: 1 }

#services are just like blog but has header, image and body
- name: "services"
  label: "Services"
  folder: test1/content/blog/posts
  create: true
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  fields:
    - { label: "Layout", name: "layout", widget: "hidden", default: "services" }
    - { label: "Title", name: "title", widget: "string" }
    - { label: "Publish Date", name: "date", widget: "datetime" }
    - { label: "Featured Image", name: "thumbnail", widget: "image" }
    - { label: "Body", name: "body", widget: "markdown" }
    - { label: "Weight", name: "weight", widget: "number", default: 1 }


#facilities, events - events have date, time, and location
- name: "facilities"
  label: "Facilities"
  folder: "test1/content/facilities"
  create: true
  slug: "{{slug}}"
  fields:
    - { label: "Layout", name: "layout", widget: "hidden", default: "facilities" }
    - { label: "Title", name: "title", widget: "string" }
    - { label: "Publish Date", name: "date", widget: "datetime" }
    - { label: "Featured Image", name: "thumbnail", widget: "image" }
    - { label: "Body", name: "body", widget: "markdown" }
    - { label: "Weight", name: "weight", widget: "number", default: 1 }


- name: "events"
  label: "Events"
  folder: "test1/content/events"
  create: true
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  fields:
    - { label: "Layout", name: "layout", widget: "hidden", default: "events" }
    - { label: "Title", name: "title", widget: "string" }
    - { label: "Publish Date", name: "date", widget: "datetime" }
    - { label: "Featured Image", name: "thumbnail", widget: "image" }
    - { label: "Body", name: "body", widget: "markdown" }
    - { label: "Weight", name: "weight", widget: "number", default: 1 }

- name: "pages"
  label: "Pages"
  folder: "test1/content"
  create: true
  slug: "{{slug}}"
  fields:
    - name: "title"
      label: "Title"
      widget: "string"
      required: true
    - name: "heading"
      label: "Heading"
      widget: "string"
      required: true
    - name: draft
      label: Draft
      widget: boolean
      default: false
      required: false
    - name: "summary"
      label: "Summary"
      widget: "string"
      hint: Max 120-150 characters
      required: false
    - name: "images"
      label: "Images"
      widget: "list"
      label_singular: "image"
      required: false
      summary: '{{fields.image}}'
      field: { name: "image", label: "Image", widget: "image", required: false, allow_multiple: false, choose_url: false}
    - name: "body"
      label: "Body"
      widget: "markdown"
    - name: "weight"
      label: "Weight"
      widget: "number"
      default: 1
    #menu is string default for pages value is main
    - name: "menu"
      label: "Menu"
      widget: "string"
      default: "main"
      required: false